# Generated by Django 3.2.7 on 2022-01-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=False),
        ),
    ]
