# Generated by Django 3.2.7 on 2022-01-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail',
            field=models.CharField(max_length=180),
        ),
    ]
