# Generated by Django 3.2.7 on 2022-04-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20220402_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
