# Generated by Django 3.2.7 on 2022-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_project_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website_url',
            field=models.URLField(null=True),
        ),
    ]
