# Generated by Django 3.2.7 on 2022-04-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_project_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_repo_url',
            field=models.URLField(null=True),
        ),
    ]
